# Generated by Django 5.2 on 2025-05-18 10:01

from django.db import migrations
from user.initialiser import create_initial_user_permissions, create_initial_user_types

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_user_types),
        migrations.RunPython(create_initial_user_permissions)
]
