//
// CreateMissedWastePickupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** DTO for creating a missed waste pickup. */
public struct CreateMissedWastePickupDto: Codable, JSONEncodable, Hashable {

    public var description: String
    public var date: String
    public var address: String

    public init(description: String, date: String, address: String) {
        self.description = description
        self.date = date
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case date
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(date, forKey: .date)
        try container.encode(address, forKey: .address)
    }
}

