//
// MissedWastePickupSearchResultDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** DTO for the result of a missed waste pickup search. */
public struct MissedWastePickupSearchResultDto: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var description: String
    public var date: String
    public var address: String
    public var status: Int
    public var userId: String

    public init(id: Int, description: String, date: String, address: String, status: Int, userId: String) {
        self.id = id
        self.description = description
        self.date = date
        self.address = address
        self.status = status
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case description
        case date
        case address
        case status
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(description, forKey: .description)
        try container.encode(date, forKey: .date)
        try container.encode(address, forKey: .address)
        try container.encode(status, forKey: .status)
        try container.encode(userId, forKey: .userId)
    }
}

