//
// UpdateMissedWastePickupStatusDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** DTO for updating the status of a missed waste pickup. */
public struct UpdateMissedWastePickupStatusDto: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var status: Int

    public init(id: Int, status: Int) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}

