/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.ActivityEditDTO
import org.openapitools.client.models.CreateReviewDTO
import org.openapitools.client.models.HTTPValidationError

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test createNewActivityApiActivitiesPost
        should("test createNewActivityApiActivitiesPost") {
            // uncomment below to test createNewActivityApiActivitiesPost
            //val name : kotlin.String = name_example // kotlin.String | 
            //val type : kotlin.Int = 56 // kotlin.Int | 
            //val latitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val longitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val address : kotlin.String = address_example // kotlin.String | 
            //val bookingUrl : kotlin.String = bookingUrl_example // kotlin.String | 
            //val description : kotlin.String = description_example // kotlin.String | 
            //val files : kotlin.collections.List<java.io.File> = /path/to/file.txt // kotlin.collections.List<java.io.File> | 
            //val heroImage : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : kotlin.Any = apiInstance.createNewActivityApiActivitiesPost(name, type, latitude, longitude, address, bookingUrl, description, files, heroImage)
            //result shouldBe ("TODO")
        }

        // to test createNewActivityReviewApiActivitiesReviewsPost
        should("test createNewActivityReviewApiActivitiesReviewsPost") {
            // uncomment below to test createNewActivityReviewApiActivitiesReviewsPost
            //val createReviewDTO : CreateReviewDTO =  // CreateReviewDTO | 
            //val result : kotlin.Any = apiInstance.createNewActivityReviewApiActivitiesReviewsPost(createReviewDTO)
            //result shouldBe ("TODO")
        }

        // to test deleteActivityApiActivitiesActivityIdDelete
        should("test deleteActivityApiActivitiesActivityIdDelete") {
            // uncomment below to test deleteActivityApiActivitiesActivityIdDelete
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.deleteActivityApiActivitiesActivityIdDelete(activityId)
            //result shouldBe ("TODO")
        }

        // to test deleteActivityImagesApiActivitiesImagesImageIdDelete
        should("test deleteActivityImagesApiActivitiesImagesImageIdDelete") {
            // uncomment below to test deleteActivityImagesApiActivitiesImagesImageIdDelete
            //val imageId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.deleteActivityImagesApiActivitiesImagesImageIdDelete(imageId)
            //result shouldBe ("TODO")
        }

        // to test deleteActivityReviewApiActivitiesReviewsReviewIdDelete
        should("test deleteActivityReviewApiActivitiesReviewsReviewIdDelete") {
            // uncomment below to test deleteActivityReviewApiActivitiesReviewsReviewIdDelete
            //val reviewId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.deleteActivityReviewApiActivitiesReviewsReviewIdDelete(reviewId)
            //result shouldBe ("TODO")
        }

        // to test getActivitiesApiActivitiesSearchGet
        should("test getActivitiesApiActivitiesSearchGet") {
            // uncomment below to test getActivitiesApiActivitiesSearchGet
            //val searchTerm : kotlin.String = searchTerm_example // kotlin.String | 
            //val sortField : kotlin.String = sortField_example // kotlin.String | 
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val categories : kotlin.String = categories_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.getActivitiesApiActivitiesSearchGet(searchTerm, sortField, sortOrder, limit, page, categories)
            //result shouldBe ("TODO")
        }

        // to test getActivitiesByLocationApiActivitiesSearchLocationGet
        should("test getActivitiesByLocationApiActivitiesSearchLocationGet") {
            // uncomment below to test getActivitiesByLocationApiActivitiesSearchLocationGet
            //val latitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val longitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val radius : kotlin.Int = 56 // kotlin.Int | 
            //val searchTerm : kotlin.String = searchTerm_example // kotlin.String | 
            //val categories : kotlin.String = categories_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.getActivitiesByLocationApiActivitiesSearchLocationGet(latitude, longitude, radius, searchTerm, categories)
            //result shouldBe ("TODO")
        }

        // to test getActivityApiActivitiesActivityIdGet
        should("test getActivityApiActivitiesActivityIdGet") {
            // uncomment below to test getActivityApiActivitiesActivityIdGet
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.getActivityApiActivitiesActivityIdGet(activityId)
            //result shouldBe ("TODO")
        }

        // to test getActivityImagesApiActivitiesImagesActivityActivityIdGet
        should("test getActivityImagesApiActivitiesImagesActivityActivityIdGet") {
            // uncomment below to test getActivityImagesApiActivitiesImagesActivityActivityIdGet
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.getActivityImagesApiActivitiesImagesActivityActivityIdGet(activityId)
            //result shouldBe ("TODO")
        }

        // to test getImageApiActivitiesImagesImageIdGet
        should("test getImageApiActivitiesImagesImageIdGet") {
            // uncomment below to test getImageApiActivitiesImagesImageIdGet
            //val imageId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.getImageApiActivitiesImagesImageIdGet(imageId)
            //result shouldBe ("TODO")
        }

        // to test getReviewsApiActivitiesReviewsGet
        should("test getReviewsApiActivitiesReviewsGet") {
            // uncomment below to test getReviewsApiActivitiesReviewsGet
            //val searchTerm : kotlin.String = searchTerm_example // kotlin.String | 
            //val sortField : kotlin.String = sortField_example // kotlin.String | 
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.getReviewsApiActivitiesReviewsGet(searchTerm, sortField, sortOrder, limit, page, activityId)
            //result shouldBe ("TODO")
        }

        // to test updateActivityApiActivitiesEditPost
        should("test updateActivityApiActivitiesEditPost") {
            // uncomment below to test updateActivityApiActivitiesEditPost
            //val activityEditDTO : ActivityEditDTO =  // ActivityEditDTO | 
            //val result : kotlin.Any = apiInstance.updateActivityApiActivitiesEditPost(activityEditDTO)
            //result shouldBe ("TODO")
        }

        // to test uploadActivityImagesApiActivitiesImagesActivityActivityIdUploadPost
        should("test uploadActivityImagesApiActivitiesImagesActivityActivityIdUploadPost") {
            // uncomment below to test uploadActivityImagesApiActivitiesImagesActivityActivityIdUploadPost
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val images : kotlin.collections.List<java.io.File> = /path/to/file.txt // kotlin.collections.List<java.io.File> | 
            //val result : kotlin.Any = apiInstance.uploadActivityImagesApiActivitiesImagesActivityActivityIdUploadPost(activityId, images)
            //result shouldBe ("TODO")
        }

        // to test uploadHeroImageApiActivitiesImagesActivityActivityIdHeroUploadPost
        should("test uploadHeroImageApiActivitiesImagesActivityActivityIdHeroUploadPost") {
            // uncomment below to test uploadHeroImageApiActivitiesImagesActivityActivityIdHeroUploadPost
            //val activityId : kotlin.Int = 56 // kotlin.Int | 
            //val image : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val result : kotlin.Any = apiInstance.uploadHeroImageApiActivitiesImagesActivityActivityIdHeroUploadPost(activityId, image)
            //result shouldBe ("TODO")
        }

    }
}
