# Generated by Django 5.2 on 2025-04-21 11:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 11, 57, 26, 872799, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 11, 57, 26, 872824, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='InterestingPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 11, 57, 26, 873161, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 11, 57, 26, 873175, tzinfo=datetime.timezone.utc))),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.interestingplace')),
            ],
        ),
    ]
