# Generated by Django 5.2 on 2025-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('S', 'Service'), ('P', 'Product'), ('H', 'Hospitality')])),
                ('image_url', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_reviewed', models.DateTimeField(null=True)),
                ('approved_by', models.CharField(null=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
