services:

  nginx:
    image: nginx:latest
    container_name: swakop-backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - auth_static:/var/www/auth/static
    networks:
      - swakop-backend
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      - authentication

  rabbitmq:
    image: rabbitmq:management
    container_name: swakop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - swakop-backend

  authentication:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: swakop-auth-service
    volumes:
      - auth_static:/app/staticfiles
    networks:
      - swakop-backend
    depends_on:
      - auth_database
    environment:
      DATABASE: ${AUTH_DB}
      USER: ${AUTH_USER}
      PASSWORD: ${AUTH_PASSWORD}
      HOST: ${AUTH_HOST}
      PORT: ${AUTH_PORT}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_IS_STAFF: ${DJANGO_SUPERUSER_IS_STAFF:-True}
      FORCE_SCRIPT_NAME: /api/auth

  health:
    build:
      context: ./health
      dockerfile: Dockerfile
    container_name: swakop-health-service
    networks:
      - swakop-backend
    depends_on:
      - health_database
    environment:
      DATABASE: ${HEALTH_DB}
      USER: ${HEALTH_USER}
      PASSWORD: ${HEALTH_PASSWORD}
      HOST: ${HEALTH_HOST}
      PORT: ${HEALTH_PORT}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}

  auth_database:
    image: postgres:latest
    container_name: swakop-auth-db
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - swakop-backend

  health_database:
    image: postgres:latest
    container_name: swakop-health-db
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: health_password
      POSTGRES_DB: health_db
    volumes:
      - health_db_data:/var/lib/postgresql/data
    networks:
      - swakop-backend

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: database-manager
    environment:
      SQLPAD_CONNECTIONS__db1__name: 
    ports:
      - "28080:8081"
    depends_on:
      - auth_database
      - health_database
    networks:
      - swakop-backend

networks:
  swakop-backend:
    driver: bridge

volumes:
  rabbitmq_data:
  auth_db_data:
  health_db_data:
  auth_static:
  
