services:
  nginx:
    image: nginx:latest
    container_name: swakop-backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - swakop-backend
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      - authentication

  rabbitmq:
    image: rabbitmq:management
    container_name: swakop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - swakop-backend

  authentication:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: swakop-auth-service
    networks:
      - swakop-backend
    depends_on:
      - auth_database
    environment:
      DATABASE: ${AUTH_DB}
      USER: ${AUTH_USER}
      PASSWORD: ${AUTH_PASSWORD}
      HOST: ${AUTH_HOST}
      PORT: ${AUTH_PORT}

  auth_database:
    image: postgres:latest
    container_name: swakop-auth-db
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - swakop-backend

networks:
  swakop-backend:
    driver: bridge

volumes:
  rabbitmq_data:
  auth_db_data: