# Generated by Django 5.2 on 2025-04-21 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationresourcepermission',
            name='permission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], max_length=10), size=None),
        ),
    ]
