# Generated by Django 5.2 on 2025-05-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicationresourcepermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='api_key_plain',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='api_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
