# Generated by Django 5.2 on 2025-05-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_api_key_plain_alter_application_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='api_key_plain',
        ),
    ]
