/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * DTO for creating a missed waste pickup.
 *
 * @param description 
 * @param date 
 * @param address 
 */


data class CreateMissedWastePickupDto (

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "date")
    val date: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String

)

