/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * DTO for the result of a missed waste pickup search.
 *
 * @param id 
 * @param description 
 * @param date 
 * @param address 
 * @param status 
 * @param userId 
 */


data class MissedWastePickupSearchResultDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "date")
    val date: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "status")
    val status: kotlin.Int,

    @Json(name = "userId")
    val userId: kotlin.String

)

