/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * DTO for updating the status of a missed waste pickup.
 *
 * @param id 
 * @param status 
 */


data class UpdateMissedWastePickupStatusDto (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "status")
    val status: kotlin.Int

)

