/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.CreateMissedWastePickupDto
import org.openapitools.client.models.HTTPValidationError
import org.openapitools.client.models.MissedWastePickupSearchResultDto
import org.openapitools.client.models.UpdateMissedWastePickupStatusDto

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test createMissedWastePickupApiWasteManagementMissedWastePickupsPost
        should("test createMissedWastePickupApiWasteManagementMissedWastePickupsPost") {
            // uncomment below to test createMissedWastePickupApiWasteManagementMissedWastePickupsPost
            //val createMissedWastePickupDto : CreateMissedWastePickupDto =  // CreateMissedWastePickupDto | 
            //val result : kotlin.Any = apiInstance.createMissedWastePickupApiWasteManagementMissedWastePickupsPost(createMissedWastePickupDto)
            //result shouldBe ("TODO")
        }

        // to test getMissedWastePickupDetailsApiWasteManagementMissedWastePickupsIdGet
        should("test getMissedWastePickupDetailsApiWasteManagementMissedWastePickupsIdGet") {
            // uncomment below to test getMissedWastePickupDetailsApiWasteManagementMissedWastePickupsIdGet
            //val id : kotlin.Int = 56 // kotlin.Int | 
            //val result : MissedWastePickupSearchResultDto = apiInstance.getMissedWastePickupDetailsApiWasteManagementMissedWastePickupsIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test getMissedWastePickupsApiWasteManagementMissedWastePickupsGet
        should("test getMissedWastePickupsApiWasteManagementMissedWastePickupsGet") {
            // uncomment below to test getMissedWastePickupsApiWasteManagementMissedWastePickupsGet
            //val searchTerm : kotlin.String = searchTerm_example // kotlin.String | 
            //val sortField : kotlin.String = sortField_example // kotlin.String | 
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.collections.List<MissedWastePickupSearchResultDto> = apiInstance.getMissedWastePickupsApiWasteManagementMissedWastePickupsGet(searchTerm, sortField, sortOrder, limit, page)
            //result shouldBe ("TODO")
        }

        // to test updateMissedWastePickupStatusApiWasteManagementMissedWastePickupsUpdateStatusPost
        should("test updateMissedWastePickupStatusApiWasteManagementMissedWastePickupsUpdateStatusPost") {
            // uncomment below to test updateMissedWastePickupStatusApiWasteManagementMissedWastePickupsUpdateStatusPost
            //val updateMissedWastePickupStatusDto : UpdateMissedWastePickupStatusDto =  // UpdateMissedWastePickupStatusDto | 
            //val result : kotlin.Any = apiInstance.updateMissedWastePickupStatusApiWasteManagementMissedWastePickupsUpdateStatusPost(updateMissedWastePickupStatusDto)
            //result shouldBe ("TODO")
        }

    }
}
