# Generated by Django 5.2 on 2025-04-21 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('updated_by', models.CharField(editable=False, max_length=50)),
            ],
        ),
    ]
