"""Added reviews

Revision ID: 4073860cb478
Revises: 54502ae3b69b
Create Date: 2025-04-24 15:50:31.403806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4073860cb478"
down_revision: Union[str, None] = "54502ae3b69b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("review_text", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_reviews_id"), "activity_reviews", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_reviews_user_id"),
        "activity_reviews",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_reviews_user_id"), table_name="activity_reviews")
    op.drop_index(op.f("ix_activity_reviews_id"), table_name="activity_reviews")
    op.drop_table("activity_reviews")
    # ### end Alembic commands ###
