"""reset migrations

Revision ID: a320a123736c
Revises:
Create Date: 2025-05-05 12:59:27.915072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision: str = "a320a123736c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("filepath", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("booking_url", sa.String(length=255), nullable=True),
        sa.Column("hero_image_id", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "point_geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["hero_image_id"], ["images.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activities_point_geom_1",
        "activities",
        ["point_geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_activities_created_by"), "activities", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_activities_hero_image_id"),
        "activities",
        ["hero_image_id"],
        unique=False,
    )
    op.create_index(op.f("ix_activities_id"), "activities", ["id"], unique=False)
    op.create_index(
        op.f("ix_activities_latitude"), "activities", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_activities_longitude"), "activities", ["longitude"], unique=False
    )
    op.create_index(
        op.f("ix_activities_updated_by"), "activities", ["updated_by"], unique=False
    )
    op.create_table(
        "activity_images",
        sa.Column("image_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("image_id", "activity_id"),
    )
    op.create_table(
        "activity_reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("review_text", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_reviews_id"), "activity_reviews", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_reviews_user_id"),
        "activity_reviews",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_reviews_user_id"), table_name="activity_reviews")
    op.drop_index(op.f("ix_activity_reviews_id"), table_name="activity_reviews")
    op.drop_table("activity_reviews")
    op.drop_table("activity_images")
    op.drop_index(op.f("ix_activities_updated_by"), table_name="activities")
    op.drop_index(op.f("ix_activities_longitude"), table_name="activities")
    op.drop_index(op.f("ix_activities_latitude"), table_name="activities")
    op.drop_index(op.f("ix_activities_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_hero_image_id"), table_name="activities")
    op.drop_index(op.f("ix_activities_created_by"), table_name="activities")
    op.drop_index(
        "idx_activities_point_geom", table_name="activities", postgresql_using="gist"
    )
    op.drop_table("activities")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
