"""Added createdAt to reviews

Revision ID: d02ab1b6e890
Revises: 4073860cb478
Create Date: 2025-04-24 16:25:52.201446

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d02ab1b6e890"
down_revision: Union[str, None] = "4073860cb478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_reviews", sa.Column("created_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity_reviews", "created_at")
    # ### end Alembic commands ###
