/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param latitude 
 * @param longitude 
 * @param type 
 * @param address 
 * @param bookingUrl 
 * @param id 
 * @param description 
 */


data class ActivityEditDTO (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,

    @Json(name = "type")
    val type: kotlin.Int,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "booking_url")
    val bookingUrl: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "description")
    val description: kotlin.String? = null

)

