/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param activityId 
 * @param rating 
 * @param review 
 */


data class CreateReviewDTO (

    @Json(name = "activity_id")
    val activityId: kotlin.Int,

    @Json(name = "rating")
    val rating: kotlin.Int,

    @Json(name = "review")
    val review: kotlin.String

)

