//
// CreateReviewDTO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateReviewDTO: Codable, JSONEncodable, Hashable {

    static let ratingRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    static let reviewRule = StringRule(minLength: 3, maxLength: 512, pattern: nil)
    public var activityId: Int
    public var rating: Int
    public var review: String

    public init(activityId: Int, rating: Int, review: String) {
        self.activityId = activityId
        self.rating = rating
        self.review = review
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activityId = "activity_id"
        case rating
        case review
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(activityId, forKey: .activityId)
        try container.encode(rating, forKey: .rating)
        try container.encode(review, forKey: .review)
    }
}

