"""Initial migration 1

Revision ID: 73560eb7f74f
Revises: 
Create Date: 2025-05-12 22:47:55.291679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73560eb7f74f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missed_waste_pickups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missed_waste_pickups_date'), 'missed_waste_pickups', ['date'], unique=False)
    op.create_index(op.f('ix_missed_waste_pickups_id'), 'missed_waste_pickups', ['id'], unique=False)
    op.create_index(op.f('ix_missed_waste_pickups_userId'), 'missed_waste_pickups', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missed_waste_pickups_userId'), table_name='missed_waste_pickups')
    op.drop_index(op.f('ix_missed_waste_pickups_id'), table_name='missed_waste_pickups')
    op.drop_index(op.f('ix_missed_waste_pickups_date'), table_name='missed_waste_pickups')
    op.drop_table('missed_waste_pickups')
    # ### end Alembic commands ###
